### ISSUE TITLE
Doesn't work with Python 3.11

### ISSUE THREAD

**Issue by xyzPeter** [veryacademy/YT-Django-Celery-Series-email-example#1]
First, thanks for creating this tutorial on YouTube and sharing the source here!

I see that this code will not run with Python 3.11. I'm getting this error:
**cannot import name 'formatargspec' from 'inspect'**

Will you update to support the latest Python version?
